package:
  name: trilinos
  version: 12.2.2
build:
  number: 0
  string: pytrilinos

source:
  fn: trilinos-12.2.2-Source.tar.bz2
  url: http://trilinos.csbsju.edu/download/files/trilinos-12.2.2-Source.tar.bz2
  md5: 90bbb175505b55878401a51a1d17463c
  patches:
      - svdi.patch
      - muelu.patch

requirements:
  build:
    - numpy 1.10.1 py27_0
    - swig
    - doxygen HEAD py27
    - cmake
    - libnetcdf HEAD py27
    - boost
  run:
    - numpy 1.10.1 py27_0
    - libnetcdf HEAD py27
    - boost

