package:
  name: cloog
  version: 0.18.4

source:
  fn: cloog-0.18.4.tar.gz
  url: http://www.bastoul.net/cloog/pages/download/count.php3?url=./cloog-0.18.4.tar.gz

requirements:
  build:
    - gmp 6.1.0
    - isl 0.15

  run:
    - gmp 6.1.0
    - isl 0.15
