package:
  name: gcc-5
  version: 5.3.0

source:
  fn: gcc-5.3.0.tar.bz2
  url: http://www.netgull.com/gcc/releases/gcc-5.3.0/gcc-5.3.0.tar.bz2

build:
  detect_binary_files_with_prefix: true # [not linux32]
  number: 0

requirements:
  build:
    # These are taken from the output of the configure scripts
    - gmp 6.1.0
    - mpfr 3.1.3
    - mpc 1.0.3
    - isl 0.15
    - cloog 0.18.4
    # Do not make gcc a build dependency (you will need to add it to the PATH manually)
  run:
    - gmp 6.1.0
    - mpfr 3.1.3
    - mpc 1.0.3
    - isl 0.15
    - cloog 0.18.4

test:
  commands:
    - gcc --help

about:
  home: http://gcc.gnu.org/
  summary: The GNU Compiler Collection
  license: GPL
