package:
  name: mpc
  version: 1.0.3

source:
  url: ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz
  fn: mpc-1.0.3.tar.gz

requirements:
  build:
    - gmp 6.1.0
    - mpfr 3.1.3
  run:
    - gmp 6.1.0
    - mpfr 3.1.3

about:
  home: http://www.multiprecision.org/
  license: GPL
  summary: Gnu Mpc is a C library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result.
