package:
  name: isl
  version: 0.15

source:
  fn: isl-0.15.tar.bz2
  url: http://isl.gforge.inria.fr/isl-0.15.tar.bz2

build:
  number: 0

requirements:
  build:
    - gmp 6.1.0
  run:
    - gmp 6.1.0

about:
  license: MIT
  summary: "isl is a thread-safe C library for manipulating sets and relations of integer points bounded by affine constraints."
