package:
  name: libnetcdf
  version: 'HEAD'
build:
  number: 0
  string: py27

source:
  git_url: https://github.com/johntfoster/netcdf-c

requirements:
  build:
    - curl
    - zlib 1.2.8 py27
    - hdf5 1.8.16 py27
  run:
    - curl
    - zlib 1.2.8 py27
    - hdf5 1.8.16 py27

test:
  commands:
    - ncdump
    - nc-config --help

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT
