package:
  name: gmp
  version: 6.1.0

source:
  fn: gmp-6.1.0.tar.bz2
  url: https://gmplib.org/download/gmp/gmp-6.1.0.tar.bz2

about:
  home: http://gmplib.org/
  license: GPL 3

test:
  files:
    - test.c
