package:
  name: doxygen
  version: 'HEAD'
build:
  number: 0
  string: py27

source:
  git_url: https://github.com/doxygen/doxygen.git

about:
  home: http://www.stack.nl/~dimitri/doxygen/index.html
  license: GNU GPL
