package:
  name: openmpi
  version: 1.10.2
build:
  number: 0
  string: py27

source:
  fn: openmpi-1.10.2.tar.bz2
  url: http://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.2.tar.bz2
  md5: b2f43d9635d2d52826e5ef9feb97fd4c

about:
  home: http://www.open-mpi.org/
  license: new BSD  (http://www.open-mpi.org/community/license.php)
